name: Feature Request
description: Suggest an idea or enhancement for this project
title: "[FEATURE] "
labels: ["Type: Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        **Before submitting, please:**
        - Check if this feature already exists in the documentation
        - Search existing issues to avoid duplicates
        - Consider whether this feature would benefit most users

  - type: textarea
    id: problem-related
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: |
        Example: "I'm always frustrated when [describe the situation]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen
      placeholder: |
        Example: "It would be great if [describe ideal solution]..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've tried
      placeholder: |
        Example: "I tried [alternative approach] but it doesn't work because..."
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe scenarios where this feature would be valuable
      placeholder: |
        Example: "This would be particularly useful when [describe situation]..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or mockups about the feature
      placeholder: |
        Include:
        - Technical constraints
        - Screenshots/mockups (if applicable)
        - Related documentation references

  - type: checkboxes
    attributes:
      label: Confirmations
      description: Please verify the following
      options:
        - label: I've checked that this feature doesn't already exist
          required: true
        - label: I've searched existing issues for similar requests
          required: true
        - label: This feature would benefit multiple users (not just my specific case)
          required: false
